# Generated by Django 3.2.25 on 2024-07-23 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='title')),
                ('subtitle', models.TextField(blank=True, null=True, verbose_name='subtitle')),
                ('img', models.ImageField(blank=True, null=True, upload_to=None, verbose_name='image_background')),
            ],
            options={
                'verbose_name': 'about',
                'verbose_name_plural': 'abouts',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='title_of_article')),
                ('subtitle', models.CharField(blank=True, max_length=250, null=True, verbose_name='name_of_article')),
                ('title2', models.CharField(blank=True, max_length=100, null=True, verbose_name='title_of_article')),
                ('desciption', models.TextField(blank=True, null=True, verbose_name='description_of_article')),
                ('img', models.ImageField(blank=True, null=True, upload_to=None, verbose_name='img_of_article')),
            ],
            options={
                'verbose_name': 'article',
                'verbose_name_plural': 'articles',
            },
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='title')),
                ('subtitle', models.TextField(blank=True, null=True, verbose_name='description_of_newsletter')),
                ('desciption', models.TextField(blank=True, null=True, verbose_name='description_of_newsletter')),
                ('img', models.ImageField(blank=True, null=True, upload_to=None, verbose_name='img_of_newsletter')),
            ],
            options={
                'verbose_name': 'newsletter',
                'verbose_name_plural': 'newsletters',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='full name')),
                ('subtitle', models.CharField(blank=True, max_length=250, null=True, verbose_name='position_work')),
                ('img', models.ImageField(blank=True, null=True, upload_to=None, verbose_name='img_of_person')),
            ],
            options={
                'verbose_name': 'team',
                'verbose_name_plural': 'teams',
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.TextField(blank=True, null=True, verbose_name='subtitle')),
            ],
            options={
                'verbose_name': 'work',
                'verbose_name_plural': 'works',
            },
        ),
    ]
