# Generated by Django 5.0.7 on 2024-08-18 15:57

import ckeditor.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='title_of_article_whole')),
                ('title_article', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='title_article')),
                ('title_article2', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='title_article2')),
                ('title_article3', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='title_article3')),
                ('subtitle', models.TextField(blank=True, max_length=200, null=True, verbose_name='read more')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='title_of_article')),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Published Date')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-published_date'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='title')),
                ('img', models.ImageField(blank=True, null=True, upload_to=None, verbose_name='img_of_newsletter')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='description_of_newsletter')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'newsletter',
                'verbose_name_plural': 'newsletters',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='full name')),
                ('subtitle', models.CharField(blank=True, max_length=250, null=True, verbose_name='position_work')),
                ('description', models.TextField(blank=True, null=True, verbose_name='story_of_member')),
                ('img', models.ImageField(blank=True, null=True, upload_to=None, verbose_name='img_of_person')),
            ],
            options={
                'verbose_name': 'team',
                'verbose_name_plural': 'teams',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('region', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='description_of_newsletter')),
            ],
            options={
                'verbose_name': 'work',
                'verbose_name_plural': 'works',
            },
        ),
        migrations.CreateModel(
            name='Articlein',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_article', models.CharField(blank=True, max_length=200, null=True, verbose_name='title article')),
                ('subtitle', models.TextField(blank=True, null=True, verbose_name='subtitle article')),
                ('img', models.ImageField(blank=True, null=True, upload_to=None, verbose_name='long image')),
                ('title_first_article', models.CharField(blank=True, max_length=200, null=True, verbose_name='title_first_article')),
                ('content1', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='content for frist p')),
                ('img1', models.ImageField(blank=True, null=True, upload_to=None, verbose_name='img of in left ')),
                ('content2', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='content for second p')),
                ('img2', models.ImageField(blank=True, null=True, upload_to=None, verbose_name='img of in left under ')),
                ('content3', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='content for last before go right')),
                ('content4', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='righ column continue left')),
                ('title_second_article', models.CharField(blank=True, max_length=200, null=True, verbose_name='title_second_article')),
                ('content5', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='content for right')),
                ('img3', models.ImageField(blank=True, null=True, upload_to=None, verbose_name='img for right  ')),
                ('content6', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='content for right')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='title')),
                ('related_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mind.article')),
            ],
            options={
                'verbose_name': 'articlein',
                'verbose_name_plural': 'articleins',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Article', to='mind.category'),
        ),
        migrations.CreateModel(
            name='Newsletterin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.ImageField(blank=True, null=True, upload_to=None, verbose_name='img_of_newsletter1')),
                ('subtitle1', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='description_of_newsletter1')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='title')),
                ('related_newsletter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mind.newsletter')),
            ],
            options={
                'verbose_name': 'newsletterin',
                'verbose_name_plural': 'newsletterins',
            },
        ),
    ]
