# Generated by Django 5.0.7 on 2024-08-18 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mind', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=None, verbose_name='long image'),
        ),
    ]
