# Generated by Django 3.2.25 on 2024-07-23 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mind', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='class_name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='class name'),
        ),
    ]
