# Generated by Django 3.2.25 on 2024-07-23 23:27

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mind', '0002_about_class_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='subtitle',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='description_of_newsletter'),
        ),
    ]
