# Generated by Django 5.0.7 on 2024-08-19 16:21

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mind', '0002_article_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='subtitle',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='subtitle for card article'),
        ),
    ]
