# Generated by Django 3.2.25 on 2024-07-23 23:30

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mind', '0003_auto_20240723_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='subtitle',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='description_of_newsletter'),
        ),
    ]
