# Generated by Django 5.0.7 on 2024-08-19 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mind', '0003_alter_article_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlein',
            name='related_article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mind.category'),
        ),
    ]
