# Generated by Django 5.0.7 on 2024-08-19 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mind', '0005_alter_articlein_related_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='title1',
        ),
        migrations.RemoveField(
            model_name='article',
            name='title_article2',
        ),
        migrations.RemoveField(
            model_name='article',
            name='title_article3',
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='prsoto def str ga'),
        ),
        migrations.AlterField(
            model_name='articlein',
            name='related_article',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mind.article'),
        ),
    ]
