# Generated by Django 5.0.7 on 2024-08-20 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mind', '0006_remove_article_title1_remove_article_title_article2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlein',
            name='related_article',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='mind.article'),
        ),
    ]
