# Generated by Django 5.0.7 on 2024-08-20 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mind', '0007_alter_articlein_related_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlein',
            name='related_article',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mind.article'),
        ),
        migrations.AlterField(
            model_name='team',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='img_of_person'),
        ),
    ]
