# Generated by Django 5.0.7 on 2024-08-22 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mind', '0009_team_slug_alter_team_description_teamin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamin',
            name='related_person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mind.team'),
        ),
    ]
